"""
Configuration management CLI commands for Rose.

Provides commands to initialize, view, and modify Rose configuration.
"""

import os
import sys
import yaml
from pathlib import Path
from typing import Optional, Dict, Any
import typer
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text

from ..core.config import get_config, RoseConfig, update_config, CompressionType, LogLevel
from ..core.util import get_logger, set_app_mode, AppMode
from ..ui.theme import get_color

# Initialize
set_app_mode(AppMode.CLI)
logger = get_logger(__name__)
console = Console()

app = typer.Typer(help="Configuration management commands")

@app.command()
def init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing configuration file"),
    template: str = typer.Option("default", "--template", "-t", help="Configuration template to use")
):
    """Initialize a default configuration file."""
    
    config_file = Path("rose.config.yaml")
    
    if config_file.exists() and not force:
        console.print(f"[{get_color('warning')}]Configuration file already exists: {config_file}[/{get_color('warning')}]")
        console.print(f"Use [{get_color('accent')}]--force[/{get_color('accent')}] to overwrite")
        raise typer.Exit(1)
    
    try:
        # Create default configuration
        default_config = {
            "# Rose Configuration File": None,
            "# Performance Settings": None,
            "parallel_workers": 4,
            "memory_limit_mb": 512,
            
            "# Feature Toggles": None,
            "enable_cache": True,
            "enable_plugins": True,
            
            "# Default Behavior": None,
            "compression_default": "none",
            "verbose_default": False,
            "build_index_default": False,
            
            "# Logging Settings": None,
            "log_level": "INFO",
            "log_to_file": True,
            
            "# UI Settings": None,
            "theme_file": "rose.theme.default.yaml",
            "enable_colors": True,
            
            "# Directory Settings": None,
            "output_directory": "output",
        }
        
        # Remove comment keys for YAML output
        yaml_config = {k: v for k, v in default_config.items() if not k.startswith("#")}
        
        # Write configuration file with comments
        with open(config_file, 'w') as f:
            f.write("# Rose Configuration File\n")
            f.write("# Generated by: rose config init\n\n")
            
            f.write("# Performance Settings\n")
            f.write(f"parallel_workers: {yaml_config['parallel_workers']}\n")
            f.write(f"memory_limit_mb: {yaml_config['memory_limit_mb']}\n\n")
            
            f.write("# Feature Toggles\n")
            f.write(f"enable_cache: {str(yaml_config['enable_cache']).lower()}\n")
            f.write(f"enable_plugins: {str(yaml_config['enable_plugins']).lower()}\n\n")
            
            f.write("# Default Behavior\n")
            f.write(f"compression_default: {yaml_config['compression_default']}\n")
            f.write(f"verbose_default: {str(yaml_config['verbose_default']).lower()}\n")
            f.write(f"build_index_default: {str(yaml_config['build_index_default']).lower()}\n\n")
            
            f.write("# Logging Settings\n")
            f.write(f"log_level: {yaml_config['log_level']}\n")
            f.write(f"log_to_file: {str(yaml_config['log_to_file']).lower()}\n\n")
            
            f.write("# UI Settings\n")
            f.write(f"theme_file: {yaml_config['theme_file']}\n")
            f.write(f"enable_colors: {str(yaml_config['enable_colors']).lower()}\n\n")
            
            f.write("# Directory Settings\n")
            f.write(f"output_directory: {yaml_config['output_directory']}\n")
        
        console.print(f"[{get_color('success')}]✓[/{get_color('success')}] Configuration file created: [{get_color('path')}]{config_file}[/{get_color('path')}]")
        console.print(f"[{get_color('muted')}]Edit the file to customize your settings[/{get_color('muted')}]")
        
    except Exception as e:
        console.print(f"[{get_color('error')}]Error creating configuration file: {e}[/{get_color('error')}]")
        raise typer.Exit(1)

@app.command()
def show(
    key: Optional[str] = typer.Argument(None, help="Specific configuration key to show"),
    format: str = typer.Option("table", "--format", "-f", help="Output format: table, yaml, json")
):
    """Show current configuration."""
    
    try:
        config = get_config()
        
        if key:
            # Show specific key
            if hasattr(config, key):
                value = getattr(config, key)
                console.print(f"[{get_color('accent')}]{key}[/{get_color('accent')}]: [{get_color('highlight')}]{value}[/{get_color('highlight')}]")
            else:
                console.print(f"[{get_color('error')}]Configuration key not found: {key}[/{get_color('error')}]")
                raise typer.Exit(1)
        else:
            # Show all configuration
            if format == "table":
                _show_config_table(config)
            elif format == "yaml":
                _show_config_yaml(config)
            elif format == "json":
                _show_config_json(config)
            else:
                console.print(f"[{get_color('error')}]Invalid format: {format}[/{get_color('error')}]")
                raise typer.Exit(1)
                
    except Exception as e:
        console.print(f"[{get_color('error')}]Error reading configuration: {e}[/{get_color('error')}]")
        raise typer.Exit(1)

@app.command()
def set(
    key: str = typer.Argument(..., help="Configuration key to set"),
    value: str = typer.Argument(..., help="Value to set"),
    config_file: Optional[str] = typer.Option(None, "--config", "-c", help="Configuration file path")
):
    """Set a configuration value."""
    
    config_path = Path(config_file) if config_file else Path("rose.config.yaml")
    
    if not config_path.exists():
        console.print(f"[{get_color('error')}]Configuration file not found: {config_path}[/{get_color('error')}]")
        console.print(f"[{get_color('muted')}]Run [{get_color('accent')}]rose config init[/{get_color('accent')}] to create one[/{get_color('muted')}]")
        raise typer.Exit(1)
    
    try:
        # Load existing configuration
        with open(config_path, 'r') as f:
            config_data = yaml.safe_load(f) or {}
        
        # Validate key exists in RoseConfig
        config = get_config()
        if not hasattr(config, key):
            console.print(f"[{get_color('error')}]Invalid configuration key: {key}[/{get_color('error')}]")
            _show_available_keys()
            raise typer.Exit(1)
        
        # Convert value to appropriate type
        converted_value = _convert_value(key, value, config)
        
        # Update configuration
        config_data[key] = converted_value
        
        # Write back to file
        with open(config_path, 'w') as f:
            yaml.dump(config_data, f, default_flow_style=False, sort_keys=False)
        
        console.print(f"[{get_color('success')}]✓[/{get_color('success')}] Set [{get_color('accent')}]{key}[/{get_color('accent')}] = [{get_color('highlight')}]{converted_value}[/{get_color('highlight')}]")
        console.print(f"[{get_color('muted')}]Configuration saved to: {config_path}[/{get_color('muted')}]")
        
    except Exception as e:
        console.print(f"[{get_color('error')}]Error setting configuration: {e}[/{get_color('error')}]")
        raise typer.Exit(1)

@app.command()
def get(
    key: str = typer.Argument(..., help="Configuration key to get"),
):
    """Get a specific configuration value."""
    
    try:
        config = get_config()
        
        if hasattr(config, key):
            value = getattr(config, key)
            console.print(f"{value}")
        else:
            console.print(f"[{get_color('error')}]Configuration key not found: {key}[/{get_color('error')}]")
            raise typer.Exit(1)
            
    except Exception as e:
        console.print(f"[{get_color('error')}]Error getting configuration: {e}[/{get_color('error')}]")
        raise typer.Exit(1)

@app.command()
def validate(
    config_file: Optional[str] = typer.Option(None, "--config", "-c", help="Configuration file path")
):
    """Validate configuration file."""
    
    config_path = Path(config_file) if config_file else Path("rose.config.yaml")
    
    if not config_path.exists():
        console.print(f"[{get_color('error')}]Configuration file not found: {config_path}[/{get_color('error')}]")
        raise typer.Exit(1)
    
    try:
        # Try to load and validate configuration
        config = get_config()
        
        console.print(f"[{get_color('success')}]✓[/{get_color('success')}] Configuration is valid")
        console.print(f"[{get_color('muted')}]Loaded from: {config._loaded_config_path or 'defaults'}[/{get_color('muted')}]")
        
        # Show any warnings
        if hasattr(config, '_validation_warnings') and config._validation_warnings:
            console.print(f"\n[{get_color('warning')}]Warnings:[/{get_color('warning')}]")
            for warning in config._validation_warnings:
                console.print(f"  [{get_color('warning')}]•[/{get_color('warning')}] {warning}")
        
    except Exception as e:
        console.print(f"[{get_color('error')}]Configuration validation failed: {e}[/{get_color('error')}]")
        raise typer.Exit(1)

def _show_config_table(config: RoseConfig):
    """Show configuration in table format."""
    
    table = Table(title="Rose Configuration")
    table.add_column("Setting", style=get_color('accent'), width=25)
    table.add_column("Value", style=get_color('highlight'), width=20)
    table.add_column("Description", style=get_color('muted'), width=40)
    
    # Performance Settings
    table.add_row("parallel_workers", str(config.parallel_workers), "Number of parallel workers")
    table.add_row("memory_limit_mb", str(config.memory_limit_mb), "Memory limit in MB")
    
    # Feature Toggles
    table.add_row("enable_cache", str(config.enable_cache), "Enable caching system")
    table.add_row("enable_plugins", str(config.enable_plugins), "Enable plugin system")
    
    # Default Behavior
    table.add_row("compression_default", config.compression_default, "Default compression type")
    table.add_row("verbose_default", str(config.verbose_default), "Default verbose mode")
    table.add_row("build_index_default", str(config.build_index_default), "Default build index")
    
    # Logging Settings
    table.add_row("log_level", config.log_level, "Logging level")
    table.add_row("log_to_file", str(config.log_to_file), "Enable file logging")
    
    # UI Settings
    table.add_row("theme_file", config.theme_file, "Theme file name")
    table.add_row("enable_colors", str(config.enable_colors), "Enable colored output")
    
    # Directory Settings
    table.add_row("output_directory", config.output_directory, "Default output directory")
    
    console.print(table)
    
    # Show file source
    if hasattr(config, '_loaded_config_path') and config._loaded_config_path:
        console.print(f"\n[{get_color('muted')}]Loaded from: {config._loaded_config_path}[/{get_color('muted')}]")

def _show_config_yaml(config: RoseConfig):
    """Show configuration in YAML format."""
    
    config_dict = {
        "parallel_workers": config.parallel_workers,
        "memory_limit_mb": config.memory_limit_mb,
        "enable_cache": config.enable_cache,
        "enable_plugins": config.enable_plugins,
        "compression_default": config.compression_default,
        "verbose_default": config.verbose_default,
        "build_index_default": config.build_index_default,
        "log_level": config.log_level,
        "log_to_file": config.log_to_file,
        "theme_file": config.theme_file,
        "enable_colors": config.enable_colors,
        "output_directory": config.output_directory,
    }
    
    yaml_output = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)
    console.print(yaml_output)

def _show_config_json(config: RoseConfig):
    """Show configuration in JSON format."""
    import json
    
    config_dict = {
        "parallel_workers": config.parallel_workers,
        "memory_limit_mb": config.memory_limit_mb,
        "enable_cache": config.enable_cache,
        "enable_plugins": config.enable_plugins,
        "compression_default": config.compression_default,
        "verbose_default": config.verbose_default,
        "build_index_default": config.build_index_default,
        "log_level": config.log_level,
        "log_to_file": config.log_to_file,
        "theme_file": config.theme_file,
        "enable_colors": config.enable_colors,
        "output_directory": config.output_directory,
    }
    
    json_output = json.dumps(config_dict, indent=2)
    console.print(json_output)

def _convert_value(key: str, value: str, config: RoseConfig):
    """Convert string value to appropriate type based on configuration field."""
    
    field_type = type(getattr(config, key))
    
    if field_type == bool:
        return value.lower() in ('true', '1', 'yes', 'on')
    elif field_type == int:
        return int(value)
    elif field_type == float:
        return float(value)
    elif key == "compression_default":
        if value not in [e.value for e in CompressionType]:
            raise ValueError(f"Invalid compression type: {value}. Valid options: {[e.value for e in CompressionType]}")
        return value
    elif key == "log_level":
        if value not in [e.value for e in LogLevel]:
            raise ValueError(f"Invalid log level: {value}. Valid options: {[e.value for e in LogLevel]}")
        return value
    else:
        return value

def _show_available_keys():
    """Show available configuration keys."""
    
    console.print(f"\n[{get_color('info')}]Available configuration keys:[/{get_color('info')}]")
    
    keys = [
        ("parallel_workers", "int", "Number of parallel workers"),
        ("memory_limit_mb", "int", "Memory limit in MB"),
        ("enable_cache", "bool", "Enable caching system"),
        ("enable_plugins", "bool", "Enable plugin system"),
        ("compression_default", "str", "Default compression (none/bz2/lz4)"),
        ("verbose_default", "bool", "Default verbose mode"),
        ("build_index_default", "bool", "Default build index"),
        ("log_level", "str", "Log level (DEBUG/INFO/WARNING/ERROR/CRITICAL)"),
        ("log_to_file", "bool", "Enable file logging"),
        ("theme_file", "str", "Theme file name"),
        ("enable_colors", "bool", "Enable colored output"),
        ("output_directory", "str", "Default output directory"),
    ]
    
    for key, type_name, description in keys:
        console.print(f"  [{get_color('accent')}]{key}[/{get_color('accent')}] ([{get_color('muted')}]{type_name}[/{get_color('muted')}]) - {description}")
